"""Changed type of job's model job_id column, added lenght of string on columns.

Revision ID: 1e1b0e587c86
Revises: ee14c03ee547
Create Date: 2023-08-06 21:55:19.597733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1b0e587c86'
down_revision = 'ee14c03ee547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'job_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'job_id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
