"""Removed user_agent column from Data, removed fetch_data column from Jobs

Revision ID: ee14c03ee547
Revises: eda2b2e8e21d
Create Date: 2023-08-06 17:58:52.176313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee14c03ee547'
down_revision = 'eda2b2e8e21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'user_agent')
    op.drop_column('jobs', 'fetch_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('fetch_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
